name = "ashutoshk"
compatibility_date = "2025-01-01"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".svelte-kit/cloudflare"

[[d1_databases]]
binding = "DB"
database_name = "ashutosh-blog"
database_id = "2fdf7146-f834-48de-aa5f-c2191e4c106d"
